spring.application.name=sistemasCorrelativas

# Conexión a Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistemasCorrelativas?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ardunita
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Spring Data JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
